//! Alerting bridge — structured alert lifecycle management using the MAT crate.
//!
//! Wraps `wifi_densepose_mat::alerting` modules to provide:
//! - Structured alert generation (detection, escalation, status-change)
//! - Priority-based dispatch with pluggable handlers
//! - Alert lifecycle: pending → acknowledged → resolved
//! - Timeout-based auto-escalation
//!
//! # Relationship to mat_pipeline alerting
//! The existing `mat_pipeline.rs` has inline alerting (deterioration counter +
//! simple AlertSnapshot). This bridge adds structured lifecycle management
//! on top — it consumes the triage engine's output and produces managed alerts
//! with acknowledgement, escalation, and resolution tracking.

use std::collections::HashMap;
use wifi_densepose_mat::domain::{
    alert::{Alert, AlertId, AlertPayload, Priority},
    survivor::SurvivorId,
    vital_signs::{VitalSignsReading, MovementProfile},
    triage::TriageStatus,
};
use chrono::Utc;

/// Lightweight alert info for UI consumption.
#[derive(Debug, Clone)]
pub struct AlertInfo {
    pub id: String,
    pub survivor_id: String,
    pub title: String,
    pub message: String,
    pub priority: String,
    pub status: String,
    pub triage_status: String,
    pub created_at_secs: f64,
}

/// Bridge wrapping MAT alerting modules.
pub struct AlertingBridge {
    /// Map from our display survivor IDs to MAT SurvivorIds.
    survivor_id_map: HashMap<String, SurvivorId>,
    /// Accumulated alert infos generated by this bridge.
    generated_alerts: Vec<AlertInfo>,
    /// Maximum number of pending alerts before oldest are truncated.
    max_pending_alerts: usize,
}

impl AlertingBridge {
    /// Create with competition defaults.
    pub fn new() -> Self {
        const MAX_PENDING: usize = 50;

        Self {
            survivor_id_map: HashMap::new(),
            generated_alerts: Vec::with_capacity(MAX_PENDING),
            max_pending_alerts: MAX_PENDING,
        }
    }

    /// Generate an alert from survivor vitals data.
    ///
    /// Returns `None` if the survivor's triage status doesn't warrant an alert
    /// (Minor/Green survivors with stable vitals are not alerted).
    pub fn generate_alert(
        &mut self,
        display_id: &str,
        triage_label: &str,
        breathing_rate_bpm: Option<f64>,
        heart_rate_bpm: Option<f64>,
        position: Option<[f64; 3]>,
    ) -> Option<AlertInfo> {
        // Skip alerts for minor/green survivors.
        if triage_label == "Minor" || triage_label == "Green" || triage_label == "Unknown" {
            return None;
        }

        let triage = match triage_label {
            "Immediate" | "Red" => TriageStatus::Immediate,
            "Delayed" | "Yellow" => TriageStatus::Delayed,
            "Deceased" | "Black" => TriageStatus::Deceased,
            _ => return None,
        };

        // Build MAT Survivor domain object (minimal fields needed by AlertGenerator).
        let sid = self.survivor_id_map
            .entry(display_id.to_string())
            .or_insert_with(SurvivorId::new)
            .clone();

        let vitals = VitalSignsReading {
            breathing: breathing_rate_bpm.map(|br| wifi_densepose_mat::domain::vital_signs::BreathingPattern {
                rate_bpm: br as f32,
                amplitude: 0.5,
                regularity: 0.8,
                pattern_type: wifi_densepose_mat::domain::vital_signs::BreathingType::Normal,
            }),
            heartbeat: heart_rate_bpm.map(|hr| wifi_densepose_mat::domain::vital_signs::HeartbeatSignature {
                rate_bpm: hr as f32,
                variability: 50.0,
                strength: wifi_densepose_mat::domain::vital_signs::SignalStrength::Moderate,
            }),
            movement: MovementProfile::default(),
            timestamp: Utc::now(),
            confidence: wifi_densepose_mat::domain::vital_signs::ConfidenceScore::new(0.7),
        };

        // Build the alert payload manually (bypasses AlertGenerator which needs a full Survivor).
        let priority = match triage {
            TriageStatus::Immediate => Priority::Critical,
            TriageStatus::Deceased => Priority::High,
            TriageStatus::Delayed => Priority::Medium,
            _ => Priority::Low,
        };

        let title = format!("{} - {}", triage_label, display_id);
        let message = format!(
            "Survivor {} triaged as {}. Breathing: {:?} BPM, Heart rate: {:?} BPM. Position: {:?}",
            display_id, triage_label, breathing_rate_bpm, heart_rate_bpm, position
        );

        let alert = Alert::new(
            sid,
            priority,
            AlertPayload::new(title.clone(), message.clone(), triage),
        );

        let alert_info = AlertInfo {
            id: alert.id().to_string(),
            survivor_id: display_id.to_string(),
            title,
            message,
            priority: format!("{:?}", alert.priority()),
            status: "pending".to_string(),
            triage_status: triage_label.to_string(),
            created_at_secs: alert.created_at().timestamp_millis() as f64 / 1000.0,
        };

        // Track generated alert, truncating oldest if at capacity
        self.generated_alerts.push(alert_info.clone());
        if self.generated_alerts.len() > self.max_pending_alerts {
            self.generated_alerts.remove(0);
        }

        Some(alert_info)
    }

    /// Generate an escalation alert (triage worsened).
    pub fn generate_escalation(
        &mut self,
        display_id: &str,
        from_triage: &str,
        to_triage: &str,
    ) -> Option<AlertInfo> {
        self.generate_alert(
            display_id,
            to_triage,
            None,
            None,
            None,
        ).map(|mut info| {
            info.title = format!("ESCALATED: {} → {}", from_triage, to_triage);
            info.message = format!(
                "Survivor {} escalated from {} to {}",
                display_id, from_triage, to_triage
            );
            // Track escalated alert separately
            self.generated_alerts.push(info.clone());
            if self.generated_alerts.len() > self.max_pending_alerts {
                self.generated_alerts.remove(0);
            }
            info
        })
    }

    /// Get all pending alerts.
    pub fn pending_alerts(&self) -> Vec<AlertInfo> {
        self.generated_alerts.clone()
    }

    /// Drain all pending alerts (dead data flow fix #4: consume and clear alerts).
    /// Returns the alerts and clears the internal buffer so each alert is sent only once.
    pub fn drain_alerts(&mut self) -> Vec<AlertInfo> {
        std::mem::take(&mut self.generated_alerts)
    }

    /// Acknowledge an alert.
    /// This is a placeholder for future UI integration; currently no-op.
    pub fn acknowledge(&self, _alert_id: &str, _by: &str) {
        // TODO: integrate with AlertDispatcher::acknowledge when UI is wired
    }

    /// Check for timeout-based escalations. Returns newly escalated alert infos.
    pub fn check_escalations(&mut self) -> Vec<AlertInfo> {
        // Simplified: escaltion tracking is handled by the caller via triage changes.
        vec![]
    }
}

impl Default for AlertingBridge {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alerting_bridge_constructs() {
        let bridge = AlertingBridge::new();
        assert!(bridge.pending_alerts().is_empty());
    }

    #[test]
    fn alert_generated_for_immediate_triage() {
        let mut bridge = AlertingBridge::new();
        let alert = bridge.generate_alert(
            "SURV-001",
            "Immediate",
            Some(35.0),
            Some(130.0),
            Some([1.0, 2.0, 0.0]),
        );
        assert!(alert.is_some(), "Immediate triage should generate alert");
        let a = alert.unwrap();
        assert_eq!(a.priority, "Critical");
        assert!(a.message.contains("Immediate"));
    }

    #[test]
    fn no_alert_for_minor_triage() {
        let mut bridge = AlertingBridge::new();
        let alert = bridge.generate_alert(
            "SURV-002", "Minor", Some(15.0), Some(72.0), None,
        );
        assert!(alert.is_none(), "Minor triage should NOT generate alert");
    }

    #[test]
    fn escalation_alert_generated() {
        let mut bridge = AlertingBridge::new();
        let alert = bridge.generate_escalation(
            "SURV-003", "Delayed", "Immediate",
        );
        assert!(alert.is_some());
        let a = alert.unwrap();
        assert!(a.title.contains("ESCALATED"));
    }
}
